### ISSUE TITLE
JSON files not generating

### ISSUE THREAD

**Issue by Liiw** [crazysnailboy/VillagerTrades#1]
Hello, 

I installed the mod along numerous other mods and when I start the game, the folders and config files were created but no JSON files within the folders. I tried enabling both options in the config file and also deleting the folder, but the newly created folders were empty.

**Comment by crazysnailboy** [comment]
Hi,

After setting the two config values to true, if you delete the vtt folders from the config directory and restart the game, it should populate them with JSON files.

Please let me know if that works, and I'll make a change for the next version so that's a bit simpler.

**Comment by crazysnailboy** [comment]
Hi,

Thanks for letting me know. I've uploaded v0.5.1 which should resolve this. Please let me know if you have any more problems :)

**Comment by Liiw** [comment]
Thank you for your quick reply, I tried the update and everything is working as intended!
