### ISSUE TITLE
Guide API dependency

### ISSUE THREAD

**Issue by frakier** [crazysnailboy/VillagerTrades#11]
Was working on something earlier today accidentally disabled Guide API.

Should have gotten a message from minecraft looking for Guide API as a dependency.
Instead I get the error...

"---- Minecraft Crash Report ----
Time: 7/22/17 9:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Vitality (vitality)
Caused by: java.lang.NoClassDefFoundError: amerifrance/guideapi/api/impl/abstraction/CategoryAbstract
	at com.raphydaphy.vitality.Vitality.preInit(Vitality.java:44)"

and then spent hours trying to figure out which of the mods I updated was causing the problem.

**Comment by crazysnailboy** [comment]
This mod doesn't have a Guide API dependency, and that crash is coming from the [Vitality](https://minecraft.curseforge.com/projects/vitality) mod. I'm not sure how this mod is involved?

**Comment by frakier** [comment]
Sorry some how I posted on the wrong page. I went to the right page, realized I was not logged in. Logged in and posted somehow on your page. I'll pay more attention next time. Again sorry about that. I was playing around with you mod yesterday guess it was because you mod was on my mind.
