### ISSUE TITLE
Should be the final issues.

### ISSUE THREAD

**Issue by Supermatt5546** [crazysnailboy/VillagerTrades#14]
This took a little longer than I expected, but I finished my tables. Unfortunately, I'm still having a little trouble. Should this work, this will hopefully be the last time I bug you about this.
Here's the files:
https://pastebin.com/6YAUrLNg
I don't think the nitwit or paleontologist contain any errors, but I included them to be safe.

**Comment by Supermatt5546** [comment]
*Here're 

Didn't let me edit the comment for some reason.

**Comment by crazysnailboy** [comment]
Which files you are having problems with?

It would help if you could zip up your files and put them on Google Drive or Dropbox or something so I don't have to cut & paste everything into separate files for testing :)

**Comment by Supermatt5546** [comment]
The dyer & the ones that share his profession give the most trouble. I'm not sure I ever did that before.

**Comment by Supermatt5546** [comment]
Oops, closed it by accident.

**Comment by Supermatt5546** [comment]
I put it on Google Drive, now what?

**Comment by Supermatt5546** [comment]
https://drive.google.com/open?id=0B6_QV97r93rDLWk5cE1uNnBuWGM

**Comment by crazysnailboy** [comment]
OK I've fixed those up for you:

[Supermatt5546.zip](https://drive.google.com/uc?export=download&id=0B1LBp40P2UyBSm1sMTMxc1BFUEk)

I don't have all the same mods installed that you do so I can't comprehensively test them but there are no parsing errors in the log when they're being loaded so they should be fine.

You'll notice I deleted a couple of your villager files as you can have multiple careers in the same file so not all of them were needed.

Any more issues let me know :)

**Comment by Supermatt5546** [comment]
I wasn't sure how to properly go about adding more careers to the same profession file, which is why I did that. Thank you very much for your help.

**Comment by crazysnailboy** [comment]
No problem :)
