### ISSUE TITLE
Redstoner villager loses all trades on a server after completing one successfully

### ISSUE THREAD

**Issue by Febilian** [crazysnailboy/VillagerTrades#2]
https://gist.github.com/Febilian/5ab41a763f82d7de91de94afb8178d59

There's the error from the server's end, since nothing was on the client. After trading some oak planks to a redstoner villager for an emerald, and triggering the particles that would indicate new trades to appear, instead the villager lost all of their trades completely - the interface simply shows no clickable arrows and both slots for trading are completely blank. Kind of like how the tinkerer's trade list looks by default, actually.

EDIT: Forgot to mention that I haven't altered the trades through JSON at all. They're the defaults.

**Comment by crazysnailboy** [comment]
Thanks for letting me know, I'll look into what's going on with that

**Comment by crazysnailboy** [comment]
Apologies for the delayed response, I broke my computer...

I've tracked down the problem to errors in the JSON file for the redstoner trades - the trade for daylist sensors has the wrong item id in it. There's also an issue in the brewer trade file where I misspelt "fermented_spider_eye".

I've pushed new versions of both of those files into the repository, downloading the JSON files and replacing the ones in the config directory should resolve the error. I'll also get some new builds out which will include these fixes in them.

[brewer.json](https://github.com/crazysnailboy/VillagerTrades/blob/master/src/main/resources/assets/vtt/data/trade_tables/brewer.json)
[redstoner.json](https://github.com/crazysnailboy/VillagerTrades/blob/master/src/main/resources/assets/vtt/data/trade_tables/redstoner.json)

Thanks again for pointing this out :)

**Comment by Febilian** [comment]
Neato, I'm glad it got figured out! I really like the concept of this mod and all the customization it allows so I'm glad that the problem wasn't a huge one.
