### ISSUE TITLE
Help with metadata

### ISSUE THREAD

**Issue by judicius** [crazysnailboy/VillagerTrades#23]
Trying to create a trade for an item with metadata. MPutils tells me the item is rockhounding_surface:fossil_logs:2

when I add the :2 to the end of the id the villager trade window shows as blank.

If I remove it, as shown with a different ID in the second trade, it trades but not the item I want it to.

`{ 
	"Profession":"minecraft:farmer",
	"Career":"fisherman",

	"Offers":{
		"Recipes":[

			{"action":"clear"},

			{"action":"add", "buy":{"id":"minecraft:emerald","Count":{"min":1,"max":1}},"sell":{"id": "rockhounding_surface:fossil_logs:2","Count":64}, "CareerLevel":1},
			{"action":"add", "buy":{"id":"minecraft:emerald","Count":{"min":1,"max":1}},"sell":{"id": "rockhounding_surface:cold_logs","Count":64}, "CareerLevel":1},
			{"action":"add", "buy":{"id":"minecraft:emerald","Count":{"min":7,"max":8}},"sell":{"id": "minecraft:fishing_rod","Count":1,"tag":{"ench":"random"}}, "CareerLevel":2}

		]
	}

}`

**Comment by judicius** [comment]
answered elsewhere

**Comment by svenhjol** [comment]
where?
