### ISSUE TITLE
Crash Report, on villager spawn?

### ISSUE THREAD

**Issue by Flabort** [crazysnailboy/VillagerTrades#7]
https://pastebin.com/bhk6UyMA

I'm sorry I have no idea what happened here, it crashed and the log seems to indicate this mod.

Edit: Now it's happening when I load up a world. Here's the report for the most recent crash, too:
https://pastebin.com/BbXUU1cR

**Comment by Flabort** [comment]
Some more info: 
The crash happens randomly after a short time in the world, or sometimes immediately after world creation.
The crash does not happen when this mod is disabled.
I updated to the newest Forge (2399) and the crash still happens.

Here are all the trade files I made so far:
https://pastebin.com/5j7YzRvu

and here is the one custom villager file I made so far:
https://pastebin.com/fZT5nYC9

Here is a copy of the profile exported from the twitch/curse app, you can duplicate my conditions by importing it to curse (includes the texture for the villager):
https://drive.google.com/open?id=0B0dRWbDnsi70dUNaZEtOY3pUaUU

**Comment by crazysnailboy** [comment]
Hi - apologies for the delayed response, I didn't notice this issue when you first raised it.

I've not installed the full pack, but I found errors in 3 of your trade files.

[cartographer.json](https://pastebin.com/8MKbT62K)<br />
[fisherman.json](https://pastebin.com/BeghgGAP)<br />
[fletcher.json](https://pastebin.com/m44gQkR0)

Do you still experience a crash when using the corrected files?

**Comment by Flabort** [comment]
Oops. Note to self: Always double check you actually set a price.

And yeah, it's OK that you didn't notice it earlier, I may have actually just been a bit impatient. I did notice when I googled you that you had been gone from... everywhere on the internet for the past few days, so likely you had some real life stuff to deal with and were busy, which I totally understand.

However, yes, with the corrected files I still experience the crash.

**Comment by Flabort** [comment]
OK, I'm rubberducking here, but when I move fisherman.json, fletcher.json, and shepherd.json to another folder (thereby resetting them to default trades), the crash stops. 
Clearly it's one of those files causing the issues, which means this is once again user error. Now to find which one of those is the cause.

**Comment by crazysnailboy** [comment]
One of the things I'm going to do with the next version is beef up the logging so that when an error occurs loading trades or villagers it'll be much clearer as to what the problem is and which file it's in. In the meantime, here's a version which has slightly better logging:

[VillagerTrades-1.11-0.6.3.jar](https://drive.google.com/uc?export=download&id=0B1LBp40P2UyBdVVOQnNlNUs5NGs)

Could you post a new crash log from this version please? I'm a bit surprised it got as far as it did with your first crash, as it's got past the loading of the file but failed to properly create the trade and I've not seen that before.

**Comment by Flabort** [comment]
Er... I just found the cause of the crash, though. :P 
Heheh, I failed to capitalize Count again. >.>
But sure, I'll first do one more test to see if I've for sure fixed it, then if I have I'll purposefully un-fix that one file and get you a crashlog.

**Comment by Flabort** [comment]
...and when I test with the unfixed files on the new jar, instead of crashing the villager just doesn't have any trades. Well, I think we can close this issue.

**Comment by crazysnailboy** [comment]
Well, not crashing is an improvement :)
