### ISSUE TITLE
[Enhancement] Make /vtt reveal careers too

### ISSUE THREAD

**Issue by Flabort** [crazysnailboy/VillagerTrades#9]
So when I use the /vtt command, I get a list of professions. In the pack I'm working on, for example, the list looks like this:

```
0: minecraft:farmer
1: minecraft:librarian
2: minecraft:priest
3: minecraft:smith
4: minecraft:butcher
5: minecraft:nitwit
6: vtt:banker
7: immersiveengineering:engineer
8: actuallyadditions:jamguy
9: actuallyadditions:engineer
10: oreshrubs:shrub_guy
```

It would be nice to be able to see the careers for these. Maybe, if I type "/vtt 1", it might show something like:
```
minecraft:librarian Careers:
1: librarian
2: cartographer
```
This way, I would be able to see what the career ids for 7, 8, 9, and 10 are so I can change their trades too.

**Comment by crazysnailboy** [comment]
It actually does this alread :)

If you type "/vtt profession 0", it'll output the careers for profession 0 like this:
```
1: farmer
   4 levels
2: fisherman
   3 levels
3: shepherd
   3 levels
4: fletcher
   3 levels
```

**Comment by Flabort** [comment]
That doesn't actually appear to work. What version of VTT does it work in?

**Comment by Flabort** [comment]
Oh, I got it working. 

It's not "/vtt profession 0", it's "/vtt profession minecraft:farmer".
